version: "3"

services:
  db:
    image: "postgres:12.3"
    ports:
      - "127.0.0.1:9696:5432"
    environment:
      - "POSTGRES_DB=db_authample"
      - "POSTGRES_USER=testtest"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
  keycloak:
    image: "quay.io/keycloak/keycloak:10.0.1"
    ports:
      - "127.0.0.1:8081:8080"
    environment:
      - "KEYCLOAK_USER=admin"
      - "KEYCLOAK_PASSWORD=${KEYCLOAK_PASSWORD}"
