keycloak:
  auth-server-url: http://localhost:8081/auth
  principal-attribute: preferred_username
  realm: SampleAuth
  resource: login-app
  bearer-only: true
server:
  servlet:
    context-path: /authample
